version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    user: root
    network_mode: "bridge"
    ports:
      - "8080:8080"
      - "5000:5000"
    environment:
      TZ: Australia/West
    volumes:
    - /data/jenkins/jenkins_home:/var/jenkins_home
    - /data/jenkins/home:/home
    - /var/run/docker.sock:/var/run/docker.sock
